#!/bin/bash

while : ; do
    curl "https://adventofcode.com/2018/day/$1/input" -H "cookie: _ga=$2; _gid=$3; session=$4" > input.txt
    grep -q '404 Not Found' input.txt || grep -q 'Please don' input.txt || break
    sleep 30s
done
